# Generated by Django 4.1.7 on 2023-03-31 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(max_length=50, verbose_name='Наименование доступа')),
            ],
            options={
                'verbose_name': 'уровень доступа',
                'verbose_name_plural': 'уровни доступа',
            },
        ),
        migrations.CreateModel(
            name='CommandNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.IntegerField(verbose_name='Номер отдела/Сокращение')),
                ('command_name', models.CharField(max_length=150, verbose_name='Наименование отдела')),
            ],
            options={
                'verbose_name': 'номер отдела',
                'verbose_name_plural': 'номера отделов',
            },
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_abr', models.CharField(max_length=10, verbose_name='Сокращенное название управления')),
                ('department_name', models.CharField(max_length=250, verbose_name='Полное название управления')),
            ],
            options={
                'verbose_name': 'управление',
                'verbose_name_plural': 'управления',
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.CreateModel(
            name='VacationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type_abr', models.CharField(max_length=10, verbose_name='Сокращенное название вида отпуска')),
                ('vacation_type_name', models.CharField(max_length=150, verbose_name='Полное название вида отпуска')),
            ],
            options={
                'verbose_name': 'вид отпуска',
                'verbose_name_plural': 'виды отпусков',
            },
        ),
        migrations.CreateModel(
            name='WritePermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_permission', models.CharField(max_length=25, verbose_name='Наименования права записи')),
            ],
            options={
                'verbose_name': 'право записи',
                'verbose_name_plural': 'права записи',
            },
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='email_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='personnel_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Табельный номер'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='show_employee',
            field=models.BooleanField(default=True, verbose_name='Отображать сотрудника'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='vacationsmodel',
            name='day_count',
            field=models.IntegerField(null=True, verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='vacationsmodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacations.employeemodel', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='vacationsmodel',
            name='vacation_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание отпуска'),
        ),
        migrations.AlterField(
            model_name='vacationsmodel',
            name='vacation_start',
            field=models.DateField(verbose_name='Начало отпуска'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='command_number_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacations.commandnumbermodel', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='department_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacations.departmentmodel', verbose_name='Управление'),
        ),
        migrations.AddField(
            model_name='vacationsmodel',
            name='vacation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacations.vacationtypemodel'),
        ),
    ]
