# Generated by Django 4.1.7 on 2023-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_accesslevelmodel_commandnumbermodel_departmentmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='days_remaining',
            field=models.IntegerField(default=0, verbose_name='Количество неиспользованных дней'),
        ),
    ]
