# Generated by Django 4.1.7 on 2023-04-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_employeeaccesswritemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccesswritemodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacations.employeemodel', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='UserFilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_filter', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('command_number_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacations.commandnumbermodel', verbose_name='Отдел')),
                ('department_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacations.departmentmodel', verbose_name='Управление')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacations.employeemodel', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'фильтр сотрудника',
                'verbose_name_plural': 'фильтры сотрудников',
            },
        ),
    ]
