# Generated by Django 4.1.7 on 2023-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_alter_employeeaccesswritemodel_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiltermodel',
            name='filter_use',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фильтр включен'),
        ),
    ]
