# Generated by Django 4.1.7 on 2023-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_userfiltermodel_filter_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiltermodel',
            name='filter_use',
        ),
        migrations.AddField(
            model_name='userfiltermodel',
            name='use_command_number_filter',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фильтр управления включен'),
        ),
        migrations.AddField(
            model_name='userfiltermodel',
            name='use_department_filter',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фильтр управления включен'),
        ),
    ]
