# Generated by Django 4.1.7 on 2023-04-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_remove_userfiltermodel_filter_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandnumbermodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacations.departmentmodel', verbose_name='Управление'),
        ),
    ]
