# Generated by Django 4.1.7 on 2023-04-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0009_yearmodel_alter_commandnumbermodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiltermodel',
            name='year_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacations.yearmodel', verbose_name='Год'),
        ),
    ]
